#!/usr/bin/env node
// Erzeugt src/mlf/chat/emoji-data.js aus emojibase-data (MIT): jedes Emoji mit Name, Gruppe,
// Kurzcodes (GitHub + iamcal/Slack/Discord-artig, vereint) und Suchwörtern, in Unicode-Reihenfolge.
// Hautfarben als fünf Varianten, wo es sie gibt. Aufruf: node tools/build-emoji.js
const fs = require('fs');
const path = require('path');
const base = path.join(__dirname, '..', 'node_modules', 'emojibase-data', 'en');
const read = (f) => JSON.parse(fs.readFileSync(path.join(base, f), 'utf8'));

const data = read('compact.json');
const short = [read('shortcodes/github.json'), read('shortcodes/iamcal.json')];
const version = JSON.parse(fs.readFileSync(path.join(base, '..', 'package.json'), 'utf8')).version;
const codesOf = (hex) => {
    const all = [];
    for (const s of short) { const v = s[hex]; for (const c of Array.isArray(v) ? v : v ? [v] : []) if (!all.includes(c)) all.push(c); }
    return all;
};

const rows = data
    .filter((e) => typeof e.group === 'number' && e.group !== 2) // 2 = component (Hautfarben, Haare)
    .sort((a, b) => a.order - b.order)
    .map((e) => {
        const row = [e.unicode, e.label, e.group, codesOf(e.hexcode).join(' '), (e.tags || []).join(' ')];
        if (e.skins && e.skins.length >= 5) row.push(e.skins.slice(0, 5).map((s) => s.unicode));
        return row;
    });

const out = `    // =========================================================================================
    // EMOJI DATA — generated by tools/build-emoji.js from emojibase-data ${version} (MIT). Do not edit.
    // =========================================================================================
    // [emoji, name, group, shortcodes, search words, [5 skin tones]?]; groups as in DCF_EMOJI_GROUPS.
    const DCF_EMOJI = ${JSON.stringify(rows)};

`;
const target = path.join(__dirname, '..', 'src', 'mlf', 'chat', 'emoji-data.js');
fs.writeFileSync(target, out);
console.log(`${rows.length} Emojis, ${(out.length / 1024).toFixed(0)} KB -> ${target}`);
