    // Colour themes (section 3b). Every role is [seed, strength]: the seed gives the hue — a number
    // in OKLCH degrees (the stock blue-grey sits at about 245) or simply a colour such as a flag
    // stripe — and strength scales the chroma the game's own colour had.
    //   s  surfaces (the dark greys)        l  lines: borders and dimmer text (defaults to s)
    //   i  ink: the light text (defaults to l, a little calmer)   a  accents (defaults to s)
    // stripe = the colours of a flag or a gradient: a thin band along header, footer, window
    // bars and menus, plus a dark, readable wash of the same colours behind the big surfaces
    // (wash: false leaves that out). flag = hard edges like a real flag. decor = a static
    // pattern over those surfaces: glitter, stripes, scanlines or grid.
    // ring = the band as a thick rim of metal, light along one edge and shadow along the other,
    // instead of a thin line.
    // The ids of 6.0 are kept, so a theme chosen then is still the one chosen now.
    const THEMES = [
        { id: 'original', group: 'Classic', label: 'Crownfall', note: 'The game’s own blue' },

        // Deluxe (6.5): colours like every theme, plus a skin from SKINS (section 3c) — textures,
        // scenery and effects over the frame of the page.
        { id: 'mc-deluxe', group: 'Games', label: 'Minecraft Deluxe', note: 'Grass, dirt, stone and XP', skin: 'minecraft',
          s: ['#866043', 1.1], l: ['#5d9c3a', 1.4], i: [110, 0.3], a: ['#7fcc3c', 1.3] },
        { id: 'satisfactory-deluxe', group: 'Games', label: 'Satisfactory Deluxe', note: 'FICSIT: steel, hazard stripes, a conveyor', skin: 'ficsit',
          s: [255, 0.5], l: ['#fa9549', 2.0], i: [255, 0.4], a: ['#fa9549', 1.5] },
        { id: 'mario-deluxe', group: 'Games', label: 'Super Mario Deluxe', note: 'World 1-1: sky, bricks and ? blocks', skin: 'mario',
          s: ['#049cd8', 1.6], l: ['#e52521', 2.0], a: ['#e52521', 1.4] },
        { id: 'zelda-deluxe', group: 'Games', label: 'Zelda Deluxe', note: 'Hyrule gold, the Triforce, fairies', skin: 'hyrule',
          s: ['#1c3d2a', 1.6], l: ['#c8a24a', 1.4], a: ['#3a9d5d', 1.3] },
        { id: 'tetris-deluxe', group: 'Games', label: 'Tetris Deluxe', note: 'The well, and every button a block', skin: 'tetris',
          s: [265, 1.3], l: ['#a000f0', 1.4], a: ['#00f0f0', 1.3] },
        { id: 'pacman-deluxe', group: 'Games', label: 'Pac-Man Deluxe', note: 'Maze walls, ghosts, a hungry footer', skin: 'pacman',
          s: [265, 1.6], l: ['#2121de', 2.4], a: ['#ffb852', 1.3] },
        { id: 'portal-deluxe', group: 'Games', label: 'Portal Deluxe', note: 'Test chamber, a portal on either side', skin: 'aperture',
          s: [250, 0.5], l: ['#00a2ff', 1.6], a: ['#ff9a00', 1.4] },
        { id: 'sonic-deluxe', group: 'Games', label: 'Sonic Deluxe', note: 'Green Hill and golden rings', skin: 'greenhill',
          s: ['#0a3d91', 1.8], l: ['#1e90ff', 1.6], a: ['#ff3b30', 1.3] },
        { id: 'pokemon-deluxe', group: 'Games', label: 'Pokémon Deluxe', note: 'The chat is a Pokédex', skin: 'pokedex',
          s: ['#3b4cca', 1.4], l: ['#ff1c1c', 1.6], a: ['#ff1c1c', 1.3] },
        { id: 'gameboy-deluxe', group: 'Games', label: 'Game Boy Deluxe', note: 'The chat is a Game Boy', skin: 'gameboy',
          s: ['#306230', 1.6], l: ['#8bac0f', 1.5], i: ['#9bbc0f', 1.0], a: ['#8bac0f', 1.3] },
        { id: 'stardew-deluxe', group: 'Games', label: 'Stardew Valley Deluxe', note: 'Wood, parchment, falling leaves', skin: 'stardew',
          s: ['#5b3a1e', 1.2], l: ['#7cb342', 1.3], a: ['#f2a33a', 1.2] },
        { id: 'hollowknight-deluxe', group: 'Games', label: 'Hollow Knight Deluxe', note: 'Hallownest dark, drifting soul', skin: 'hallownest',
          s: [255, 0.8], l: [235, 1.0], a: ['#8fb8ff', 1.2] },
        { id: 'wow-deluxe', group: 'Games', label: 'World of Warcraft Deluxe', note: 'Gold frames, red buttons, an XP bar', skin: 'wow',
          s: ['#34445e', 1.4], l: ['#c8912f', 1.5], i: ['#f2d27a', 0.45], a: ['#f0a81c', 1.6] },
        { id: 'tardis', group: 'Film & TV', label: 'TARDIS', note: 'The chat is a police box', skin: 'tardis',
          s: ['#0f3d73', 1.6], l: ['#3a70b0', 1.3], i: [240, 0.4], a: ['#8ec5ff', 1.3] },
        // 6.16: seven more for Film & TV (section 3e). No logos, posters or fonts of the originals —
        // their motifs, colours and lettering, drawn anew (Greasy Fork code rules: copyright).
        { id: 'spn-deluxe', group: 'Film & TV', label: 'Supernatural', note: 'A devil’s trap, a salt line, embers', skin: 'hunters',
          s: ['#1a1714', 1.2], l: ['#c8902e', 1.3], i: [60, 0.25], a: ['#c8902e', 1.3] },
        { id: 'bb-deluxe', group: 'Film & TV', label: 'Breaking Bad', note: 'Periodic tiles, desert yellow, blue crystal', skin: 'heisenberg',
          s: ['#1e4d2b', 1.4], l: ['#326947', 1.5], a: ['#6fd3ff', 1.3] },
        { id: 'bttf-deluxe', group: 'Film & TV', label: 'Back to the Future', note: 'Time circuits, flux capacitor, fire trails', skin: 'outatime',
          s: ['#23262d', 1.0], l: ['#ff8a00', 1.5], a: ['#ff5a1f', 1.4] },
        { id: 'eeaao-deluxe', group: 'Film & TV', label: 'Everything Everywhere', note: 'Googly eyes that watch you, the bagel', skin: 'multiverse',
          s: ['#2a131a', 1.4], l: ['#c8102e', 1.6], i: ['#fefcfa', 0.3], a: ['#c8102e', 1.4] },
        { id: 'starwars-deluxe', group: 'Film & TV', label: 'Star Wars', note: 'The crawl, lightsabers, a hologram chat', skin: 'farfaraway',
          s: [250, 0.5], l: ['#ffe81f', 1.4], a: ['#4fb3ff', 1.4] },
        { id: 'vertigo-deluxe', group: 'Film & TV', label: 'Vertigo', note: 'Saul Bass: the spiral, the fall', skin: 'saulbass',
          s: ['#9e3218', 1.4], l: ['#d74219', 1.6], i: ['#fffff2', 0.3], a: ['#d74219', 1.5] },
        { id: 'cinema-deluxe', group: 'Film & TV', label: 'Cinema', note: 'Velvet curtain, marquee lights, popcorn', skin: 'cinema',
          s: ['#4a0a12', 1.4], l: ['#d4a64a', 1.5], a: ['#d4a64a', 1.4] },
        // Books (6.17)
        { id: 'lostbookshop-deluxe', group: 'Books', label: 'The Lost Bookshop', note: 'Der verschwundene Buchladen: blue spines, ivy, the yellow house', skin: 'lostbookshop',
          s: ['#0b1622', 1.3], l: ['#2E4947', 1.4], a: ['#e8c46a', 1.4] },
        { id: 'readingnook-deluxe', group: 'Books', label: 'Reading Nook', note: 'Tea, a book page, a knitted blanket, fairy lights', skin: 'readingnook',
          s: ['#2b1d17', 1.3], l: ['#c98a4b', 1.4], i: ['#f6eedb', 0.3], a: ['#c9a24a', 1.4] },
        // Music (6.18, section 3g)
        { id: 'aerzte-deluxe', group: 'Music', label: 'Die Ärzte', note: 'HELL orange, DUNKEL magenta, a bloodshot eye that watches you', skin: 'aerzte',
          s: [30, 0.3], l: ['#ff4e00', 1.6], a: ['#ff4e00', 1.5] },
        { id: 'linkinpark-deluxe', group: 'Music', label: 'Linkin Park', note: 'Sprayed concrete, a stencil, black and yellow, [brackets]', skin: 'lpark',
          s: [80, 0.25], l: ['#f6d80a', 1.5], a: ['#f6d80a', 1.4] },
        { id: 'kraftklub-deluxe', group: 'Music', label: 'Kraftklub', note: 'Red, black and white, stripes, yellow tickets, matchstick eyes', skin: 'kraftklub',
          s: [25, 0.35], l: ['#e2231a', 1.6], a: ['#ffd400', 1.5] },
        { id: 'goethe-deluxe', group: 'Music', label: 'Goethes Erben', note: 'A dark stage, cyan light, faceless figures, a line of verse', skin: 'goethe',
          s: ['#0b1e44', 1.3], l: ['#5fb8e0', 1.4], a: ['#8ce1ff', 1.4] },
        { id: 'samsa-deluxe', group: 'Music', label: 'Samsas Traum', note: 'An etched plate, a beetle crawling, candles, deep water', skin: 'samsa',
          s: ['#1d3c52', 1.2], l: ['#8a7a58', 1.3], a: ['#e6c98a', 1.3] },
        { id: 'prinzpi-deluxe', group: 'Music', label: 'Prinz Pi', note: 'Rebel lilac, a spinning record, a compass without north', skin: 'prinzpi',
          s: ['#22194F', 1.4], l: ['#674E85', 1.5], a: ['#b7a6d6', 1.4] },
        // Signature themes: each for one account only (owner), offered and applied while that
        // account is signed in (section 3d, themeVisible).
        { id: 'sig-dreaming', group: 'Signature', owner: 'DreamingLucie', label: 'Dreaming', note: 'For DreamingLucie: a soft trans-pastel night', skin: 'dreaming',
          s: ['#2a1f4a', 1.6], l: ['#f5a9b8', 1.4], i: ['#f5a9b8', 0.6], a: ['#5bcefa', 1.3] },
        { id: 'sig-bricks', group: 'Signature', owner: ['DreamingLegoGirl', 'CuteLegoGirl'], label: 'Brick Builder', note: 'For DreamingLegoGirl: bricks and studs', skin: 'bricks',
          s: [250, 0.25], l: ['#ffcd03', 1.4], a: ['#d01012', 1.3] },
        { id: 'sig-highroller', group: 'Signature', owner: 'NuceLoire', label: 'High Roller', note: 'For NuceLoire: felt, gold and chips', skin: 'casino',
          s: ['#0b5d2e', 1.3], l: ['#d4af37', 1.5], i: [90, 0.3], a: ['#d4af37', 1.4] },
        { id: 'sig-ninkasi', group: 'Signature', owner: 'ninkasi1001', label: 'Ninkasi', note: 'For ninkasi1001: amber ale, foam and clay tablets', skin: 'ninkasi',
          s: ['#3a2210', 1.4], l: ['#e8a33d', 1.5], i: [75, 0.3], a: ['#f2b233', 1.4] },
        { id: 'midnight', group: 'Classic', label: 'Midnight',  note: 'Deep navy',     s: [268, 1.5],  a: [262, 1.2] },
        { id: 'amethyst', group: 'Classic', label: 'Amethyst',  note: 'Violet',        s: [305, 1.15], a: [305, 1.1] },
        { id: 'rose',     group: 'Classic', label: 'Rose',      note: 'Soft pink',     s: [355, 1.1],  a: [355, 1.1] },
        { id: 'crimson',  group: 'Classic', label: 'Crimson',   note: 'Deep red',      s: [22, 1.4],   l: [22, 1.5],  a: [25, 1.2] },
        { id: 'copper',   group: 'Classic', label: 'Copper',    note: 'Warm brown',    s: [50, 1.1],   a: [50, 1.1] },
        { id: 'mocha',    group: 'Classic', label: 'Mocha',     note: 'Coffee',        s: [65, 0.9],   l: [60, 1.0],  a: [45, 1.0] },
        { id: 'emerald',  group: 'Classic', label: 'Emerald',   note: 'Green',         s: [160, 1.1],  a: [160, 1.05] },
        { id: 'forest',   group: 'Classic', label: 'Forest',    note: 'Moss and pine', s: [140, 1.3],  a: [125, 1.2] },
        { id: 'ocean',    group: 'Classic', label: 'Ocean',     note: 'Teal',          s: [200, 1.2],  a: [200, 1.1] },
        { id: 'graphite', group: 'Classic', label: 'Graphite',  note: 'Plain grey',    s: [245, 0.1],  a: [245, 0.2] },

        { id: 'trans', group: 'Pride', label: 'Trans', note: 'Blue, pink and white', flag: true,
          s: ['#5bcefa', 2.2], l: ['#f5a9b8', 2.4], i: ['#f5a9b8', 0.8], a: ['#f5a9b8', 1.4],
          stripe: ['#5bcefa', '#f5a9b8', '#ffffff', '#f5a9b8', '#5bcefa'] },
        { id: 'rainbow', group: 'Pride', label: 'Rainbow', note: 'The Pride flag', flag: true,
          s: [290, 0.7], l: [290, 0.9], a: [300, 1.2],
          stripe: ['#e40303', '#ff8c00', '#ffed00', '#008026', '#004dff', '#750787'] },
        { id: 'progress', group: 'Pride', label: 'Progress', note: 'Progress Pride', flag: true,
          s: [265, 0.8], l: ['#f5a9b8', 1.6], a: ['#5bcefa', 1.2],
          stripe: ['#000000', '#784f17', '#5bcefa', '#f5a9b8', '#ffffff', '#e40303', '#ff8c00', '#ffed00', '#008026', '#004dff', '#750787'] },
        { id: 'lesbian', group: 'Pride', label: 'Lesbian', note: 'Orange, white and pink', flag: true,
          s: ['#d52d00', 1.2], l: ['#d162a4', 1.6], i: ['#ff9a56', 0.6], a: ['#d162a4', 1.3],
          stripe: ['#d52d00', '#ef7627', '#ff9a56', '#ffffff', '#d162a4', '#b55690', '#a30262'] },
        { id: 'gay', group: 'Pride', label: 'Gay', note: 'Green, white and blue', flag: true,
          s: ['#3d1a78', 1.4], l: ['#26ceaa', 1.6], a: ['#26ceaa', 1.2],
          stripe: ['#078d70', '#26ceaa', '#98e8c1', '#ffffff', '#7bade2', '#5049cc', '#3d1a78'] },
        { id: 'bi', group: 'Pride', label: 'Bi', note: 'Pink, purple and blue', flag: true,
          s: ['#9b4f96', 1.6], l: ['#d60270', 1.5], a: ['#0038a8', 1.4],
          stripe: ['#d60270', '#d60270', '#9b4f96', '#0038a8', '#0038a8'] },
        { id: 'pan', group: 'Pride', label: 'Pan', note: 'Pink, yellow and blue', flag: true,
          s: ['#21b1ff', 1.5], l: ['#ff218c', 1.8], a: ['#ff218c', 1.3],
          stripe: ['#ff218c', '#ffd800', '#21b1ff'] },
        { id: 'nonbinary', group: 'Pride', label: 'Nonbinary', note: 'Yellow, white, purple, black', flag: true,
          s: ['#9c59d1', 1.5], l: ['#9c59d1', 1.3], i: ['#fcf434', 0.5], a: ['#9c59d1', 1.3],
          stripe: ['#fcf434', '#ffffff', '#9c59d1', '#2c2c2c'] },
        { id: 'genderfluid', group: 'Pride', label: 'Genderfluid', note: 'Pink, purple and blue', flag: true,
          s: ['#2f3cbe', 1.5], l: ['#c011d7', 1.6], a: ['#ff76a4', 1.3],
          stripe: ['#ff76a4', '#ffffff', '#c011d7', '#000000', '#2f3cbe'] },
        { id: 'ace', group: 'Pride', label: 'Ace', note: 'Black, grey, white, purple', flag: true,
          s: [320, 0.5], l: ['#800080', 1.4], a: ['#800080', 1.3],
          stripe: ['#000000', '#a3a3a3', '#ffffff', '#800080'] },
        { id: 'aro', group: 'Pride', label: 'Aro', note: 'Greens, white and grey', flag: true,
          s: ['#3da542', 1.2], l: ['#a7d379', 1.3], a: ['#3da542', 1.2],
          stripe: ['#3da542', '#a7d379', '#ffffff', '#a9a9a9', '#000000'] },

        { id: 'unicorn', group: 'Moods', label: 'Unicorn', note: 'Pastel, with sparkles', decor: 'glitter',
          s: ['#c9b6ff', 2.0], l: ['#ffb3de', 2.0], i: ['#b8ffd9', 0.8], a: ['#8fe3d0', 1.3],
          stripe: ['#ffb3de', '#c9b6ff', '#a7e8ff', '#b8ffd9', '#fff3b0'] },
        { id: 'glitter', group: 'Moods', label: 'Glitter', note: 'Pink and silver, sparkling', decor: 'glitter',
          s: ['#ff8fd8', 1.3], l: ['#e0c8ff', 1.4], a: ['#ff8fd8', 1.4],
          stripe: ['#ffd1f1', '#f4f4ff', '#ff8fd8', '#f4f4ff', '#ffd1f1'] },
        { id: 'antifa', group: 'Moods', label: 'Antifa', note: 'Red and black, against fascism', flag: true,
          s: [25, 0.2], l: ['#e3000f', 2.5], i: [25, 0.3], a: ['#e3000f', 1.6],
          stripe: ['#e3000f', '#e3000f', '#111111', '#111111'] },
        { id: 'punk', group: 'Moods', label: 'Punk', note: 'Hot pink, acid green', flag: true, decor: 'stripes',
          s: [330, 0.4], l: ['#ff2e88', 2.6], i: [330, 0.5], a: ['#b6ff00', 1.6],
          stripe: ['#ff2e88', '#111111', '#b6ff00', '#111111', '#ff2e88'] },
        { id: 'vaporwave', group: 'Moods', label: 'Vaporwave', note: 'Pink, cyan and lilac',
          s: ['#b967ff', 1.8], l: ['#01cdfe', 1.6], a: ['#ff71ce', 1.4],
          stripe: ['#ff71ce', '#01cdfe', '#05ffa1', '#b967ff', '#fffb96'] },
        { id: 'synthwave', group: 'Moods', label: 'Synthwave', note: 'Retro sunset grid', decor: 'grid', tint: '#ff6ad5',
          s: ['#2b1055', 2.0], l: ['#ff6ad5', 1.8], a: ['#ff9a3c', 1.4],
          stripe: ['#2b1055', '#7597de', '#ff6ad5', '#ff9a3c'] },
        { id: 'cyberpunk', group: 'Moods', label: 'Cyberpunk', note: 'Neon yellow and cyan', decor: 'scanlines',
          s: ['#0d1b4c', 1.3], l: ['#fcee0a', 1.6], i: [230, 0.6], a: ['#00f0ff', 1.3],
          stripe: ['#fcee0a', '#00f0ff', '#ff003c'] },
        { id: 'matrix', group: 'Moods', label: 'Matrix', note: 'Green on black', decor: 'scanlines',
          s: ['#00ff41', 1.4], l: ['#00ff41', 1.6], i: ['#00ff41', 1.4], a: ['#00ff41', 1.4],
          stripe: ['#003b00', '#008f11', '#00ff41'] },
        { id: 'aurora', group: 'Moods', label: 'Aurora', note: 'Northern lights',
          s: [230, 1.2], l: ['#00ffa3', 1.5], a: ['#dc1fff', 1.3],
          stripe: ['#00ffa3', '#03e1ff', '#dc1fff'] },
        { id: 'lava', group: 'Moods', label: 'Lava', note: 'Red, orange and ember',
          s: ['#ff3d00', 1.4], l: ['#ff9100', 1.6], a: ['#ff9100', 1.3],
          stripe: ['#ff3d00', '#ff9100', '#ffd600'] },
        { id: 'sunset', group: 'Moods', label: 'Sunset', note: 'Dusk to dawn',
          s: ['#6c5b7b', 1.4], l: ['#f67280', 1.5], a: ['#f8b195', 1.3],
          stripe: ['#355c7d', '#6c5b7b', '#c06c84', '#f67280', '#f8b195'] },
        { id: 'halloween', group: 'Moods', label: 'Halloween', note: 'Pumpkin and witch', flag: true,
          s: ['#6a0dad', 1.3], l: ['#ff7518', 1.6], a: ['#ff7518', 1.3],
          stripe: ['#ff7518', '#1b1b1b', '#6a0dad'] },

        // Games: the colours a game is known by, and a pattern that recalls it. tint = pattern
        // colour where the accent is not the right one.
        { id: 'minecraft', group: 'Games', label: 'Minecraft', note: 'Grass, dirt and stone', flag: true, decor: 'pixels',
          s: ['#866043', 1.3], l: ['#5d9c3a', 1.8], i: [110, 0.5], a: ['#7fcc3c', 1.4],
          stripe: ['#5d9c3a', '#5d9c3a', '#866043', '#866043', '#7f7f7f'] },
        { id: 'satisfactory', group: 'Games', label: 'Satisfactory', note: 'FICSIT orange and steel', flag: true, decor: 'hazard', tint: '#fa9549',
          s: [255, 0.5], l: ['#fa9549', 2.0], i: [255, 0.4], a: ['#fa9549', 1.5],
          stripe: ['#fa9549', '#2b2b30', '#fa9549', '#2b2b30', '#fa9549', '#2b2b30'] },
        { id: 'mario', group: 'Games', label: 'Super Mario', note: 'Red, blue and brick', flag: true, decor: 'bricks',
          s: ['#049cd8', 1.6], l: ['#e52521', 2.0], a: ['#e52521', 1.4],
          stripe: ['#e52521', '#049cd8', '#fbd000', '#43b047'] },
        { id: 'zelda', group: 'Games', label: 'Zelda', note: 'Hyrule green and gold', decor: 'triangles', tint: '#e8c667',
          s: ['#1c3d2a', 1.6], l: ['#c8a24a', 1.4], a: ['#3a9d5d', 1.3],
          stripe: ['#2e7d32', '#c8a24a', '#2f5a8b'] },
        { id: 'tetris', group: 'Games', label: 'Tetris', note: 'Seven tetrominoes', flag: true, decor: 'blocks',
          s: [265, 1.3], l: ['#a000f0', 1.4], a: ['#00f0f0', 1.3],
          stripe: ['#00f0f0', '#f0f000', '#a000f0', '#00f000', '#f00000', '#0000f0', '#f0a000'] },
        { id: 'pacman', group: 'Games', label: 'Pac-Man', note: 'Maze blue and ghosts', flag: true, decor: 'dots', tint: '#ffe600',
          s: [265, 1.6], l: ['#2121de', 2.4], a: ['#ffb852', 1.3],
          stripe: ['#ff0000', '#ffb8ff', '#00ffff', '#ffb852'] },
        { id: 'portal', group: 'Games', label: 'Portal', note: 'Blue portal, orange portal', flag: true,
          s: [250, 0.5], l: ['#00a2ff', 1.6], a: ['#ff9a00', 1.4],
          stripe: ['#00a2ff', '#00a2ff', '#ff9a00', '#ff9a00'] },
        { id: 'sonic', group: 'Games', label: 'Sonic', note: 'Blue, rings and Green Hill', decor: 'checker', tint: '#c97d3c',
          s: ['#0a3d91', 1.8], l: ['#1e90ff', 1.6], a: ['#ff3b30', 1.3],
          stripe: ['#0066cc', '#ffcc00', '#d0021b'] },
        { id: 'pokemon', group: 'Games', label: 'Pokémon', note: 'Poké Ball red and white', flag: true,
          s: ['#3b4cca', 1.4], l: ['#ff1c1c', 1.6], a: ['#ff1c1c', 1.3],
          stripe: ['#ff1c1c', '#ff1c1c', '#222224', '#ffffff', '#ffffff'] },
        { id: 'gameboy', group: 'Games', label: 'Game Boy', note: 'Four shades of green', flag: true, decor: 'pixels',
          s: ['#306230', 1.6], l: ['#8bac0f', 1.5], i: ['#9bbc0f', 1.0], a: ['#8bac0f', 1.3],
          stripe: ['#0f380f', '#306230', '#8bac0f', '#9bbc0f'] },
        { id: 'stardew', group: 'Games', label: 'Stardew Valley', note: 'Farm greens and wood',
          s: ['#5b3a1e', 1.2], l: ['#7cb342', 1.3], a: ['#f2a33a', 1.2],
          stripe: ['#7cb342', '#f2a33a', '#5b3a1e', '#6ec1e4'] },
        { id: 'hollowknight', group: 'Games', label: 'Hollow Knight', note: 'Hallownest blue-grey', wash: false,
          s: [255, 0.8], l: [235, 1.0], a: ['#8fb8ff', 1.2],
          stripe: ['#2c3547', '#9db1d6', '#e9eef5', '#9db1d6', '#2c3547'] },
        // A request: the gold ring of the logo as the rim of header and footer, the yellow and
        // orange of the W as accents, the blue-grey of the globe behind everything. No wash — a
        // gold wash would turn that blue brown.
        { id: 'wow', group: 'Games', label: 'World of Warcraft', note: 'Gold ring on Azeroth blue', ring: true, wash: false,
          s: ['#34445e', 1.4], l: ['#c8912f', 1.5], i: ['#f2d27a', 0.45], a: ['#f0a81c', 1.6],
          stripe: ['#6e3f0e', '#c98a2c', '#f7dc7a', '#d9a53a', '#8a5418', '#d9a53a', '#f7dc7a', '#c98a2c', '#6e3f0e'] },

        { id: 'dracula', group: 'Editor themes', label: 'Dracula', note: 'Purple and pink',
          s: ['#282a36', 2.0], l: ['#6272a4', 1.4], a: ['#bd93f9', 1.4], wash: false,
          stripe: ['#ff79c6', '#bd93f9', '#8be9fd', '#50fa7b', '#f1fa8c', '#ffb86c', '#ff5555'] },
        { id: 'nord', group: 'Editor themes', label: 'Nord', note: 'Arctic blue-grey',
          s: ['#2e3440', 1.0], l: ['#4c566a', 1.0], a: ['#88c0d0', 1.1], wash: false,
          stripe: ['#8fbcbb', '#88c0d0', '#81a1c1', '#5e81ac'] },
        { id: 'catppuccin', group: 'Editor themes', label: 'Catppuccin', note: 'Mocha with mauve',
          s: ['#1e1e2e', 1.6], l: ['#585b70', 1.3], a: ['#cba6f7', 1.4], wash: false,
          stripe: ['#f5e0dc', '#f5c2e7', '#cba6f7', '#89b4fa', '#94e2d5', '#a6e3a1', '#f9e2af', '#fab387'] },
        { id: 'gruvbox', group: 'Editor themes', label: 'Gruvbox', note: 'Retro warm',
          s: [70, 0.6], l: [70, 0.8], a: ['#8ec07c', 1.2], wash: false,
          stripe: ['#fb4934', '#fabd2f', '#b8bb26', '#8ec07c', '#83a598', '#d3869b'] },
        { id: 'tokyonight', group: 'Editor themes', label: 'Tokyo Night', note: 'Night blue and violet',
          s: ['#1a1b26', 1.6], l: ['#414868', 1.3], a: ['#7aa2f7', 1.3], wash: false,
          stripe: ['#7aa2f7', '#bb9af7', '#7dcfff', '#9ece6a'] },
        { id: 'solarized', group: 'Editor themes', label: 'Solarized', note: 'Deep teal',
          s: ['#002b36', 2.4], l: ['#586e75', 1.3], a: ['#268bd2', 1.2], wash: false,
          stripe: ['#b58900', '#cb4b16', '#dc322f', '#d33682', '#6c71c4', '#268bd2', '#2aa198', '#859900'] },

        { id: 'custom', group: 'Your own', label: 'Custom', note: 'Pick hue and accent' },
    ];
